import Head from "next/head"

const about = () => {
    return ( 
        <div>
            <Head>
                <title>About - Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1 className='text-4xl mb-5 font-bold'>About page</h1>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quidem dolorum labore neque maiores tempora molestias fugiat, porro explicabo nobis iste est rerum soluta laudantium ab error eaque veritatis debitis ea perspiciatis, minus enim repudiandae iusto nesciunt velit. Quae, obcaecati amet voluptatum eius itaque beatae expedita distinctio voluptate, libero quisquam commodi!</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem temporibus autem blanditiis laudantium rem cum aut, possimus reiciendis quod minima nisi culpa ipsa debitis nam dolores exercitationem tempore? Aspernatur natus, suscipit eaque nisi voluptate saepe aliquid accusantium eum dolorum atque est? Vitae, officia repellendus eaque molestiae iure exercitationem eum! Illo fuga itaque maiores necessitatibus nisi distinctio rerum laboriosam eum commodi!</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officia perferendis quia expedita, laborum excepturi assumenda vitae inventore repellendus esse numquam.</p>
            </div>
        </div>
    );
}
 
export default about;