import Head from 'next/head'

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Home - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl mb-5 font-bold'>Welcome to homepage</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque mollitia tempore, natus iure quibusdam, commodi totam fugit placeat, aut reprehenderit aliquam ipsa temporibus quod excepturi!</p>
    </div>
  )
}